export const CoreColorsVariables = [
'neutral-opaque-0',
'neutral-opaque-3',
'neutral-opaque-6',
'neutral-opaque-10',
'neutral-opaque-20',
'neutral-opaque-30',
'neutral-opaque-40',
'neutral-opaque-50',
'neutral-opaque-60',
'neutral-opaque-70',
'neutral-opaque-80',
'neutral-opaque-90',
'neutral-opaque-100',
'neutral-transparent-0',
'neutral-transparent-3',
'neutral-transparent-6',
'neutral-transparent-10',
'neutral-transparent-20',
'neutral-transparent-30',
'neutral-transparent-40',
'neutral-transparent-50',
'neutral-transparent-60',
'neutral-transparent-70',
'neutral-transparent-80',
'neutral-transparent-90',
'neutral-transparent-100',
'accent-0',
'accent-3',
'accent-6',
'accent-10',
'accent-20',
'accent-30',
'accent-40',
'accent-50',
'accent-60',
'accent-70',
'accent-80',
'accent-90',
'accent-100',
'danger-0',
'danger-3',
'danger-6',
'danger-10',
'danger-20',
'danger-30',
'danger-40',
'danger-50',
'danger-60',
'danger-70',
'danger-80',
'danger-90',
'danger-100',
] as const;
export const SemanticColorsVariables = [
'surface-0',
'surface-1',
'surface-2',
'surface-minus-1',
'stroke',
'divider',
'shadow-1',
'disabled-text',
'subdued-heading',
'subdued-text',
'text',
'heading',
'accent-focus-stroke',
'accent-link',
'accent-color-text',
'accent-color-surface',
'accent-tint-text',
'accent-tint-surface',
'danger-focus-stroke',
'danger-link',
'danger-color-text',
'danger-color-surface',
'danger-tint-text',
'danger-tint-surface',
] as const;
export const MajorScaleDimensionsVariables = [
'major-scale-1',
'major-scale-2',
'major-scale-3',
'major-scale-4',
'major-scale-5',
'major-scale-6',
'major-scale-7',
'major-scale-8',
'major-scale-9',
'major-scale-10',
'major-scale-11',
'major-scale-12',
'major-scale-13',
'major-scale-14',
] as const;
export const MinorScaleDimensionsVariables = [
'minor-scale-1',
'minor-scale-2',
'minor-scale-3',
'minor-scale-4',
'minor-scale-5',
'minor-scale-6',
'minor-scale-7',
'minor-scale-8',
'minor-scale-9',
'minor-scale-10',
'minor-scale-11',
'minor-scale-12',
'minor-scale-13',
'minor-scale-14',
'minor-scale-15',
'minor-scale-16',
'minor-scale-17',
'minor-scale-18',
] as const;
export const ExtraDimensionsVariables = [
'extra-0',
'extra-1',
'extra-half',
'extra-third',
'extra-fourth',
] as const;
export const TypographyFamiliesVariables = [
'family-sans',
] as const;
export const TypographyWeightsVariables = [
'weight-normal',
'weight-medium',
'weight-semi-bold',
] as const;
export const TypographyTrackingVariables = [
'tracking-1',
'tracking-2',
'tracking-3',
'tracking-4',
'tracking-5',
] as const;
export const TypographyLeadingVariables = [
'leading-1',
'leading-2',
'leading-3',
'leading-4',
] as const;
